### ISSUE TITLE
Implement minimal support for event channels

### ISSUE THREAD

**Issue by carlpaten** [CRust-OS/CRust-OS#13]
Xen equivalent to interrupts. Uses `__HYPERVISOR_event_channel_op`.

Enables:
- #15 
- #16

**Comment by carlpaten** [comment]
Tentatively implemented in dbf1b03, but requires testing.

**Comment by carlpaten** [comment]
http://wiki.osdev.org/Interrupts

**Comment by kanetkarster** [comment]
"Minimal" support is achieved.
