### ISSUE TITLE
Implement non-overlapping lockless ring buffer

### ISSUE THREAD

**Issue by carlpaten** [CRust-OS/CRust-OS#22]
Used by the console and XenStore. Documented in section 6.7 of the book.

Enables:
- #9
- #26
- #36

**Comment by sacooper** [comment]
A basic implementation exists in commit 9aa599380055115180ef5616f9a28ce9adca1197, although it requires some reorganization

**Comment by carlpaten** [comment]
The fact that we have console output means that this is tentatively finished.
