### ISSUE TITLE
Basic Memory Allocation

### ISSUE THREAD

**Issue by kanetkarster** [CRust-OS/CRust-OS#33]
- Write a simple "Waterfall" allocator
- port the `alloc` library

Requires:
- #34

**Comment by kanetkarster** [comment]
added in 00c336cd4b368f12b34ad0b9422c350423a14877

**Comment by carlpaten** [comment]
Requires panic support, as in #34.

**Comment by carlpaten** [comment]
@kanetkarster ported dlmalloc to Crust, but we're still running into issues.

**Comment by carlpaten** [comment]
Good job Jit.

**Comment by kanetkarster** [comment]
added in f9691558f4cf10b2b11bb5a8b035b60ca3ae1ecb
