### ISSUE TITLE
Panic support

### ISSUE THREAD

**Issue by carlpaten** [CRust-OS/CRust-OS#34]
Rust implements "panics" (equivalent to C++ exceptions). They're used throughout the standard library, including when allocating memory through `Box::new`.

To support panics, we need to implement `::rt::begin_unwind` and possibly `::rt::begin_unwind_fmt`. A good first implementation would print to the emergency console and immediately crash.

Enables:
- #33

**Comment by carlpaten** [comment]
I believe this worked before the Rust compiler switched from `rust_begin_unwind` to `rust_fail`. Fixing in M3.

**Comment by kanetkarster** [comment]
Based off a recommendation from ["Set Up Rust"](http://os.phil-opp.com/set-up-rust.html) we'll focus on adding this feature later. Currently, panicking will simply print an error message as CRust closes
