### ISSUE TITLE
Implement stdout via guest console

### ISSUE THREAD

**Issue by carlpaten** [CRust-OS/CRust-OS#9]
We've already implemented support for printing to the _Hypervisor console_ (also called "debugging console" or "emergency console"), which can be read via `xl dmesg`. However, it would be nice to support printing to the _guest console_, if only as a way to provide a meaningful `stdout` for Crust applications.

Requires:
#22

**Comment by sacooper** [comment]
A basic implementation exists in 9aa599380055115180ef5616f9a28ce9adca1197, although it requires some reorganization

**Comment by carlpaten** [comment]
Section 6.7 of the book has information.

**Comment by sacooper** [comment]
This is completed. Users can use the write!/writeln! Macros with STDOUT now.
